name: personal_budget
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.0.2
  go_router: ^5.1.1
  gsheets: ^0.4.2
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  date_time_picker: ^2.1.0 
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  riverpod_generator: ^1.0.4
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true
